# Generated by Django 4.1.2 on 2022-12-10 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('process01', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process01')),
                ('process02', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process02')),
                ('process03', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process03')),
                ('process04', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process04')),
                ('process05', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process05')),
                ('process06', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process06')),
                ('process07', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process07')),
                ('process08', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process08')),
                ('process09', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process09')),
                ('process10', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process10')),
                ('process11', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process11')),
                ('process12', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='process12')),
                ('Username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
