# Generated by Django 4.1.2 on 2022-12-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name=''),
        ),
    ]
