# Generated by Django 4.1.2 on 2022-12-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_trans', '0002_imageupload_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='email',
        ),
    ]
