# Generated by Django 4.1.2 on 2022-10-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_trans', '0002_rename_files_imageupload_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='images',
            new_name='files',
        ),
    ]
